### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by pedroccm** [WebStew/bullet#1]
I'm trying to run this project but I am getting:
ENOENT: no such file or directory, uv_chdir

Can anyone help me?

**Comment by WebStew** [comment]
Hi @pedroccm.

Can you write down the steps you are taking?

**Comment by Toriki07** [comment]
I have same issues
The steps:
Git clone https://github.com/WebStew/bullet.git
npm install
react-native run-ios

**Comment by andremartingo** [comment]
Hi, I have the same issue. I followed same steps as Toriki07.

**Comment by WebStew** [comment]
HI All,

Apologies for the delay. This is a [expo.io](https://expo.io/) React Native project so you will have to setup Expo and run the project that way. I hope this helps and let me know how you get on.

**Comment by WebStew** [comment]
Essentially :

`npm install exp -g`

Then clone the repository and within the project folder :

```
npm install
exp start
```
